Repository davidhu2000/kube-knots, pull requests merged in 2023-03, with the labels that each got.

#212 chore: add semantic commit workflow to validate PR title and add labels
  .github/workflows/docs.yaml
  .github/workflows/pr-checks.yaml
Labels: chore

#213 docs: add installation instruction for macos
  app/docs/docs/connect-to-cluster.md
  app/docs/docs/contributing/_category_.json
  app/docs/docs/features/_category_.json
  app/docs/docs/installation/first-open-error.png
  app/docs/docs/installation/index.md
  app/docs/docs/installation/install-app.gif
  app/docs/docs/installation/second-open-warning.png
  app/docs/src/pages/downloads.tsx
  app/docs/src/pages/index.tsx
Labels: docs

#214 chore: update frontend depdenencies
  app/docs/package.json
  app/kube-knots/package.json
  package.json
  yarn.lock
Labels: chore

#215 chore: update rust to 1.68.0, and update crates to latest version
  .github/dependabot.yml
  .github/workflows/pr-checks.yaml
  app/kube-knots/src-tauri/Cargo.lock
  app/kube-knots/src-tauri/Cargo.toml
Labels: chore

#217 docs: update downloads page with link to install docs
  .github/workflows/release.yaml
  app/docs/src/pages/downloads.tsx
Labels: docs

#220 feat: Improve app update flow
  app/kube-knots/src-tauri/tauri.conf.json
  app/kube-knots/src/layout.tsx
  app/kube-knots/src/settings/update-button.tsx
Labels: feat

#222 docs: split install docs based on platform
  .github/pull_request_template.md
  app/docs/docs/installation/01-macos.md
  app/docs/docs/installation/02-linux.md
  app/docs/docs/installation/03-windows.md
  app/docs/docs/installation/_category_.json
  app/docs/docs/installation/img/macos-first-open-error.png
  app/docs/docs/installation/img/macos-install-app.gif
  app/docs/docs/installation/img/macos-second-open-warning.png
Labels: docs

#221 chore: fix cargo check ci workflow
  .github/workflows/ci.yaml
Labels: chore

#224 feat: add transition animation to update button
  app/kube-knots/src/settings/update-button.tsx
Labels: feat

#225 docs: fix features page title to use consistent casing
  app/docs/docs/features/02-overview-cluster.md
  app/docs/docs/features/04-resource-creation.md
  app/docs/docs/features/05-resource-actions.md
  app/docs/docs/features/06-pod-logs.md
  app/docs/docs/features/07-notifications.md
Labels: docs

#226 fix: hide update button whenever no updates are available
  app/kube-knots/src/settings/update-button.tsx
Labels: fix

#227 chore: add-gh-action-dependabot config
  .github/dependabot.yml
Labels: chore

#229 chore: update release workflow to update gist and trigger docs
  .github/helpers/update-gist.js
  .github/release.yml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
Labels: chore

#231 docs: remove duplicate title on root page, improve description
  app/docs/docusaurus.config.js
  app/docs/src/pages/downloads.tsx
  app/docs/src/pages/index.tsx
Labels: docs

#232 docs: add subtitle on the root page
  app/docs/src/pages/index.tsx
Labels: docs

#235 fix: job table header schedule to show as `Image`
  app/kube-knots/src/workloads/jobs.tsx
Labels: fix

#236 chore: add error log to all error results for better debug-ability
  app/kube-knots/src-tauri/Cargo.lock
  app/kube-knots/src-tauri/Cargo.toml
  app/kube-knots/src-tauri/src/cluster/namespaces.rs
  app/kube-knots/src-tauri/src/cluster/node_metrics.rs
  app/kube-knots/src-tauri/src/cluster/nodes.rs
  app/kube-knots/src-tauri/src/internal/client.rs
  app/kube-knots/src-tauri/src/internal/resources.rs
  app/kube-knots/src-tauri/src/workloads/pod_metrics.rs
  app/kube-knots/src-tauri/src/workloads/pods.rs
Labels: chore

#239 fix: reduce update check frequency to only check on window focus
  app/kube-knots/src/settings/update-button.tsx
Labels: fix

#240 docs: fix link typo in footer
  app/docs/docusaurus.config.js
Labels: docs

#242 docs: update social card
  app/docs/docusaurus.config.js
  app/docs/static/img/kube-knots-social-card.png
Labels: docs

#247 docs: integrate search with algolia
  app/docs/docusaurus.config.js
Labels: docs

#241 feat: add functionality to filter pod logs
  app/kube-knots/src/components/pod-logs.tsx
  app/kube-knots/src/layout.tsx
Labels: feat

#248 fix: missing executable in path on macos/linux
  app/kube-knots/src-tauri/Cargo.lock
  app/kube-knots/src-tauri/Cargo.toml
  app/kube-knots/src-tauri/src/main.rs
Labels: fix

#250 feat: update release job to build specific macos architecture builds
  .github/helpers/update-gist.js
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: feat

#251 chore: on release publish, trigger a new docs deploy
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
Labels: chore

#252 docs: update download links to account for m1/intel mac builds
  app/docs/src/pages/downloads.tsx
Labels: docs

#255 fix: remove initial value from queries to show properly loading state
  .github/workflows/ci.yaml
  app/docs/package.json
  app/kube-knots/package.json
  app/kube-knots/src/clusters/nodes.tsx
  app/kube-knots/src/components/resource-table.tsx
  app/kube-knots/src/hooks/use-multi-resource-list.ts
  app/kube-knots/src/hooks/use-resource-list.ts
  app/kube-knots/src/providers/namespaces-provider.tsx
  app/kube-knots/src/root-view/metrics-overview.tsx
  app/kube-knots/src/root-view/resources-overview.tsx
  app/kube-knots/src/workloads/pods.tsx
Labels: fix

#256 chore: improve release workflow to reduce some if conditions
  .github/workflows/release.yaml
Labels: chore

#257 docs: add docs on app labeled as damaged on apple silicon
  app/docs/docs/installation/01-macos.md
Labels: docs

#258 docs: remove footer theme so it toggles with the theme
  app/docs/docusaurus.config.js
Labels: docs

#259 chore: add download link to main readme
  README.md
Labels: chore

#260 feat: add pod disruption budget page
  app/kube-knots/src-tauri/src/configurations/mod.rs
  app/kube-knots/src-tauri/src/configurations/pod_disruption_budgets.rs
  app/kube-knots/src-tauri/src/main.rs
  app/kube-knots/src/configurations/pod-disruption-budgets.tsx
  app/kube-knots/src/hooks/use-resource-list.ts
  app/kube-knots/src/router.tsx
Labels: feat

#261 feat: implement basic telemetry using umami and add custom event to track app version
  app/docs/docs/telemetry.md
  app/kube-knots/index.html
  app/kube-knots/src/app.tsx
  app/kube-knots/src/telemetry.ts
Labels: feat

#262 docs: add umami faq link to telemetry doc
  app/docs/docs/telemetry.md
Labels: docs

#263 fix: handle condition when umami is undefined on initial launch
  app/kube-knots/index.html
  app/kube-knots/src/telemetry.ts
Labels: fix

#264 docs: fix installation instruction link on download page
  app/docs/src/pages/downloads.tsx
Labels: docs

#267 docs: fix installation link on downloads page
  app/docs/src/pages/downloads.tsx
  app/docs/src/pages/index.tsx
Labels: doc

#266 chore(deps): update npm dependencies
  app/docs/package.json
  app/kube-knots/package.json
  package.json
  yarn.lock
Labels: chore(deps)

#268 docs: add linux installation documentations
  app/docs/docs/installation/02-linux.md
Labels: docs

#269 docs: add windows installation instructions
  README.md
  app/docs/docs/installation/03-windows.md
  app/docs/docs/installation/img/windows-error-01.png
  app/docs/docs/installation/img/windows-error-02.png
  app/docs/docs/installation/img/windows-install-01.png
  app/docs/docs/installation/img/windows-install-02.png
Labels: docs

#270 feat: enable devtools on prod builds, tighten down API allowlist for improved security
  app/kube-knots/src-tauri/Cargo.lock
  app/kube-knots/src-tauri/Cargo.toml
  app/kube-knots/src-tauri/tauri.conf.json
Labels: feat

#272 fix: update cargo toml dependencies to include process in allowList
  app/kube-knots/src-tauri/Cargo.toml
Labels: fix

#276 feat: add functionality to get logs for jobs
  app/kube-knots/src-tauri/src/main.rs
  app/kube-knots/src-tauri/src/workloads/jobs.rs
  app/kube-knots/src/components/pod-logs.tsx
  app/kube-knots/src/components/resource-table.tsx
  app/kube-knots/src/workloads/jobs.tsx
Labels: feat

#278 docs: update macOS Silicon Install Instruction (Quarantine Error)
  app/docs/docs/installation/01-macos.md
Labels: docs

#281 feat: update search functionality to support regex
  app/kube-knots/src/hooks/use-search.tsx
Labels: feat

#282 docs: update installation doc title
  app/docs/docs/installation/01-macos.md
  app/docs/docs/installation/02-linux.md
  app/docs/docs/installation/03-windows.md
Labels: docs

#283 docs: setup umami integration for doc analytics
  app/docs/docusaurus.config.js
  app/docs/src/pages/downloads.tsx
  app/docs/src/pages/index.tsx
Labels: docs

#284 chore: optimize rendering on table, prevent table rerender if overlay exists
  app/kube-knots/src/components/base/table.tsx
  app/kube-knots/src/components/resource-table.tsx
  app/kube-knots/src/hooks/use-resource-actions.ts
  app/kube-knots/src/hooks/use-resource-list.ts
Labels: chore

#285 chore: optimize query-wrapper-rerender
  app/kube-knots/src/clusters/nodes.tsx
  app/kube-knots/src/components/base/table.tsx
  app/kube-knots/src/components/query-wrapper.tsx
  app/kube-knots/src/components/resource-table.tsx
  app/kube-knots/src/layout.tsx
Labels: chore

#286 fix: fix missing jobName error when requesting job logs
  app/kube-knots/src/components/pod-logs.tsx
Labels: fix
